### ISSUE TITLE
Remove global state

### ISSUE THREAD

**Issue by brazdil** [ouadev/proc_maps_parser#1]
Hey @ouadev,
Just used your parser in one of our unit tests to verify the memory layout, saved us a bit of time - thanks. :)

I would just like to point out a design choice I think you could avoid, and that is the fact that pmparser_next() relies on global state. This makes it difficult to do multiple readings of the `maps` file in memory and compare them at the end of the test. We simply went into the data struct and iterate over the linked list ourselves, but the _next() method was a source of confusion.

Cheers,
David

**Comment by ouadev** [comment]
Hey @davidbrazdil , 
Sorry for the late reply, and thank you for your observation. Indeed, it's bad design. I didn't think someone would use this stuff, ;), that's I didn't pay much attention.

Just fixed it.
