### ISSUE TITLE
c needs to be int

### ISSUE THREAD

**Issue by dongahn** [ouadev/proc_maps_parser#3]
Great tool! I just found the parse routine forms an infinite loop on our Linux Power little endian systems.

butte5{dahn}85: uname -a
Linux butte5 4.11.0-44.2.1.el7a.ppc64le #1 SMP Thu Nov 9 02:48:01 EST 2017 ppc64le ppc64le ppc64le GNU/Linux

And I believe this [code](https://github.com/ouadev/proc_maps_parser/blob/master/pmparser.c#L36) needs to be changed to:

`int c`

to correctly deal with EOF.

https://stackoverflow.com/questions/11057259/fgetc-checking-eof/11057279

**Comment by ouadev** [comment]
Hey @dongahn ,

Thank for the note. I fixed it, it turns out I don't need use getc at all.

Fixed.
